prompt --application/pages/page_00028
begin
--   Manifest
--     PAGE: 00028
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.05.31'
,p_release=>'24.1.2'
,p_default_workspace_id=>6744683248743557788
,p_default_application_id=>119982
,p_default_id_offset=>18154610827278837756
,p_default_owner=>'WKSP_INOAUG230ETHIX'
);
wwv_flow_imp_page.create_page(
 p_id=>28
,p_name=>'Create Invoice'
,p_alias=>'MANAGE-INVOICE'
,p_page_mode=>'MODAL'
,p_step_title=>'Create Invoice'
,p_autocomplete_on_off=>'OFF'
,p_page_template_options=>'#DEFAULT#:ui-dialog--stretch'
,p_protection_level=>'C'
,p_page_component_map=>'21'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(2544224980136299582)
,p_plug_name=>'DETAILS'
,p_region_template_options=>'#DEFAULT#'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(9836528545008038233)
,p_plug_display_sequence=>30
,p_query_type=>'SQL'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'select ER_SERVICE_INVOICE_DETAILS_ID,',
'       SERVICE_INVOICE_ID,',
'       ER_SERVICE_INVOICE_SERVICE_ITEM,',
'       ER_SERVICE_INVOICE_DETAILS_SERVICE_QUANTITY,',
'       ER_SERVICE_INVOICE_DETAILS_ITEM_RATE,',
'       ER__SERVICE_INVOICE_DETAILS_TOTAL_PRICE,',
'       ER__SERVICE_INVOICE_DETAILS_TAX_AMT,',
'       ER__SERVICE_INVOICE_DETAILS_DISCOUNT_AMT,',
'       ER__SERVICE_INVOICE_DETAILS_NET_TOTAL,',
'       STATUS',
'  from ER_SERVICE_INVOICE_DETAILS WHERE SERVICE_INVOICE_ID = :P28_SERVICE_INVOICE_ID'))
,p_plug_source_type=>'NATIVE_IG'
,p_plug_display_condition_type=>'ITEM_IS_NOT_NULL'
,p_plug_display_when_condition=>'P28_SERVICE_INVOICE_ID'
,p_prn_units=>'INCHES'
,p_prn_paper_size=>'LETTER'
,p_prn_width=>11
,p_prn_height=>8.5
,p_prn_orientation=>'HORIZONTAL'
,p_prn_page_header_font_color=>'#000000'
,p_prn_page_header_font_family=>'Helvetica'
,p_prn_page_header_font_weight=>'normal'
,p_prn_page_header_font_size=>'12'
,p_prn_page_footer_font_color=>'#000000'
,p_prn_page_footer_font_family=>'Helvetica'
,p_prn_page_footer_font_weight=>'normal'
,p_prn_page_footer_font_size=>'12'
,p_prn_header_bg_color=>'#EEEEEE'
,p_prn_header_font_color=>'#000000'
,p_prn_header_font_family=>'Helvetica'
,p_prn_header_font_weight=>'bold'
,p_prn_header_font_size=>'10'
,p_prn_body_bg_color=>'#FFFFFF'
,p_prn_body_font_color=>'#000000'
,p_prn_body_font_family=>'Helvetica'
,p_prn_body_font_weight=>'normal'
,p_prn_body_font_size=>'10'
,p_prn_border_width=>.5
,p_prn_page_header_alignment=>'CENTER'
,p_prn_page_footer_alignment=>'CENTER'
,p_prn_border_color=>'#666666'
);
wwv_flow_imp_page.create_region_column(
 p_id=>wwv_flow_imp.id(2544225259468299584)
,p_name=>'ER_SERVICE_INVOICE_DETAILS_ID'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'ER_SERVICE_INVOICE_DETAILS_ID'
,p_data_type=>'NUMBER'
,p_session_state_data_type=>'VARCHAR2'
,p_is_query_only=>true
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>30
,p_attribute_01=>'Y'
,p_use_as_row_header=>false
,p_enable_sort_group=>false
,p_is_primary_key=>true
,p_include_in_export=>false
);
wwv_flow_imp_page.create_region_column(
 p_id=>wwv_flow_imp.id(2544225338736299585)
,p_name=>'SERVICE_INVOICE_ID'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'SERVICE_INVOICE_ID'
,p_data_type=>'NUMBER'
,p_session_state_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>40
,p_attribute_01=>'N'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>false
,p_is_primary_key=>false
,p_default_type=>'ITEM'
,p_default_expression=>'P28_SERVICE_INVOICE_ID'
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_imp_page.create_region_column(
 p_id=>wwv_flow_imp.id(2544225426697299586)
,p_name=>'ER_SERVICE_INVOICE_SERVICE_ITEM'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'ER_SERVICE_INVOICE_SERVICE_ITEM'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_TEXT_FIELD'
,p_heading=>'Service Item'
,p_heading_alignment=>'LEFT'
,p_display_sequence=>50
,p_value_alignment=>'LEFT'
,p_attribute_05=>'BOTH'
,p_is_required=>false
,p_max_length=>10
,p_enable_filter=>true
,p_filter_operators=>'C:S:CASE_INSENSITIVE:REGEXP'
,p_filter_is_required=>false
,p_filter_text_case=>'MIXED'
,p_filter_exact_match=>true
,p_filter_lov_type=>'DISTINCT'
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>true
);
wwv_flow_imp_page.create_region_column(
 p_id=>wwv_flow_imp.id(2544225490457299587)
,p_name=>'ER_SERVICE_INVOICE_DETAILS_SERVICE_QUANTITY'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'ER_SERVICE_INVOICE_DETAILS_SERVICE_QUANTITY'
,p_data_type=>'NUMBER'
,p_is_query_only=>false
,p_item_type=>'NATIVE_NUMBER_FIELD'
,p_heading=>'Quantity'
,p_heading_alignment=>'RIGHT'
,p_display_sequence=>60
,p_value_alignment=>'RIGHT'
,p_attribute_03=>'left'
,p_attribute_04=>'decimal'
,p_is_required=>true
,p_enable_filter=>true
,p_filter_is_required=>false
,p_filter_lov_type=>'NONE'
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>true
);
wwv_flow_imp_page.create_region_column(
 p_id=>wwv_flow_imp.id(2544225650383299588)
,p_name=>'ER_SERVICE_INVOICE_DETAILS_ITEM_RATE'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'ER_SERVICE_INVOICE_DETAILS_ITEM_RATE'
,p_data_type=>'NUMBER'
,p_is_query_only=>false
,p_item_type=>'NATIVE_NUMBER_FIELD'
,p_heading=>'Item Rate'
,p_heading_alignment=>'RIGHT'
,p_display_sequence=>70
,p_value_alignment=>'RIGHT'
,p_attribute_03=>'left'
,p_attribute_04=>'decimal'
,p_is_required=>false
,p_enable_filter=>true
,p_filter_is_required=>false
,p_filter_lov_type=>'NONE'
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>true
);
wwv_flow_imp_page.create_region_column(
 p_id=>wwv_flow_imp.id(2544225698001299589)
,p_name=>'ER__SERVICE_INVOICE_DETAILS_TOTAL_PRICE'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'ER__SERVICE_INVOICE_DETAILS_TOTAL_PRICE'
,p_data_type=>'NUMBER'
,p_is_query_only=>false
,p_item_type=>'NATIVE_NUMBER_FIELD'
,p_heading=>'Total Price'
,p_heading_alignment=>'RIGHT'
,p_display_sequence=>80
,p_value_alignment=>'RIGHT'
,p_attribute_03=>'left'
,p_attribute_04=>'decimal'
,p_is_required=>true
,p_enable_filter=>true
,p_filter_is_required=>false
,p_filter_lov_type=>'NONE'
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>true
);
wwv_flow_imp_page.create_region_column(
 p_id=>wwv_flow_imp.id(2544225809928299590)
,p_name=>'ER__SERVICE_INVOICE_DETAILS_TAX_AMT'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'ER__SERVICE_INVOICE_DETAILS_TAX_AMT'
,p_data_type=>'NUMBER'
,p_is_query_only=>false
,p_item_type=>'NATIVE_NUMBER_FIELD'
,p_heading=>'Tax Amount'
,p_heading_alignment=>'RIGHT'
,p_display_sequence=>90
,p_value_alignment=>'RIGHT'
,p_attribute_03=>'left'
,p_attribute_04=>'decimal'
,p_is_required=>true
,p_enable_filter=>true
,p_filter_is_required=>false
,p_filter_lov_type=>'NONE'
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>true
);
wwv_flow_imp_page.create_region_column(
 p_id=>wwv_flow_imp.id(2544225968159299591)
,p_name=>'ER__SERVICE_INVOICE_DETAILS_DISCOUNT_AMT'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'ER__SERVICE_INVOICE_DETAILS_DISCOUNT_AMT'
,p_data_type=>'NUMBER'
,p_is_query_only=>false
,p_item_type=>'NATIVE_NUMBER_FIELD'
,p_heading=>'Discount Amount'
,p_heading_alignment=>'RIGHT'
,p_display_sequence=>100
,p_value_alignment=>'RIGHT'
,p_attribute_03=>'left'
,p_attribute_04=>'decimal'
,p_is_required=>false
,p_enable_filter=>true
,p_filter_is_required=>false
,p_filter_lov_type=>'NONE'
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>true
);
wwv_flow_imp_page.create_region_column(
 p_id=>wwv_flow_imp.id(2544226015731299592)
,p_name=>'ER__SERVICE_INVOICE_DETAILS_NET_TOTAL'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'ER__SERVICE_INVOICE_DETAILS_NET_TOTAL'
,p_data_type=>'NUMBER'
,p_is_query_only=>false
,p_item_type=>'NATIVE_NUMBER_FIELD'
,p_heading=>'Net Total Amount'
,p_heading_alignment=>'RIGHT'
,p_display_sequence=>110
,p_value_alignment=>'RIGHT'
,p_attribute_03=>'left'
,p_attribute_04=>'decimal'
,p_is_required=>true
,p_enable_filter=>true
,p_filter_is_required=>false
,p_filter_lov_type=>'NONE'
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>true
);
wwv_flow_imp_page.create_region_column(
 p_id=>wwv_flow_imp.id(3042467633054519863)
,p_name=>'APEX$ROW_ACTION'
,p_item_type=>'NATIVE_ROW_ACTION'
,p_display_sequence=>20
);
wwv_flow_imp_page.create_region_column(
 p_id=>wwv_flow_imp.id(3042467693973519864)
,p_name=>'APEX$ROW_SELECTOR'
,p_item_type=>'NATIVE_ROW_SELECTOR'
,p_display_sequence=>10
,p_attribute_01=>'Y'
,p_attribute_02=>'Y'
,p_attribute_03=>'N'
);
wwv_flow_imp_page.create_region_column(
 p_id=>wwv_flow_imp.id(3136245880541328647)
,p_name=>'STATUS'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'STATUS'
,p_data_type=>'VARCHAR2'
,p_session_state_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>160
,p_attribute_01=>'N'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>false
,p_is_primary_key=>false
,p_default_type=>'STATIC'
,p_default_expression=>'Y'
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_imp_page.create_interactive_grid(
 p_id=>wwv_flow_imp.id(2544225172580299583)
,p_internal_uid=>20698835999859137339
,p_is_editable=>true
,p_edit_operations=>'i:u:d'
,p_lost_update_check_type=>'VALUES'
,p_add_row_if_empty=>true
,p_submit_checked_rows=>false
,p_lazy_loading=>false
,p_requires_filter=>false
,p_select_first_row=>true
,p_fixed_row_height=>true
,p_pagination_type=>'SCROLL'
,p_show_total_row_count=>true
,p_show_toolbar=>true
,p_enable_save_public_report=>false
,p_enable_subscriptions=>true
,p_enable_flashback=>true
,p_define_chart_view=>true
,p_enable_download=>true
,p_download_formats=>'CSV:HTML:XLSX:PDF'
,p_enable_mail_download=>true
,p_fixed_header=>'PAGE'
,p_show_icon_view=>false
,p_show_detail_view=>false
);
wwv_flow_imp_page.create_ig_report(
 p_id=>wwv_flow_imp.id(3136255089677331707)
,p_interactive_grid_id=>wwv_flow_imp.id(2544225172580299583)
,p_static_id=>'212908660'
,p_type=>'PRIMARY'
,p_default_view=>'GRID'
,p_show_row_number=>false
,p_settings_area_expanded=>true
);
wwv_flow_imp_page.create_ig_report_view(
 p_id=>wwv_flow_imp.id(3136255341645331707)
,p_report_id=>wwv_flow_imp.id(3136255089677331707)
,p_view_type=>'GRID'
,p_srv_exclude_null_values=>false
,p_srv_only_display_columns=>true
,p_edit_mode=>false
);
wwv_flow_imp_page.create_ig_report_column(
 p_id=>wwv_flow_imp.id(3136255866578331709)
,p_view_id=>wwv_flow_imp.id(3136255341645331707)
,p_display_seq=>1
,p_column_id=>wwv_flow_imp.id(2544225259468299584)
,p_is_visible=>true
,p_is_frozen=>false
);
wwv_flow_imp_page.create_ig_report_column(
 p_id=>wwv_flow_imp.id(3136256749269331713)
,p_view_id=>wwv_flow_imp.id(3136255341645331707)
,p_display_seq=>2
,p_column_id=>wwv_flow_imp.id(2544225338736299585)
,p_is_visible=>true
,p_is_frozen=>false
);
wwv_flow_imp_page.create_ig_report_column(
 p_id=>wwv_flow_imp.id(3136257642482331716)
,p_view_id=>wwv_flow_imp.id(3136255341645331707)
,p_display_seq=>3
,p_column_id=>wwv_flow_imp.id(2544225426697299586)
,p_is_visible=>true
,p_is_frozen=>false
);
wwv_flow_imp_page.create_ig_report_column(
 p_id=>wwv_flow_imp.id(3136258565349331719)
,p_view_id=>wwv_flow_imp.id(3136255341645331707)
,p_display_seq=>4
,p_column_id=>wwv_flow_imp.id(2544225490457299587)
,p_is_visible=>true
,p_is_frozen=>false
);
wwv_flow_imp_page.create_ig_report_column(
 p_id=>wwv_flow_imp.id(3136259411282331722)
,p_view_id=>wwv_flow_imp.id(3136255341645331707)
,p_display_seq=>5
,p_column_id=>wwv_flow_imp.id(2544225650383299588)
,p_is_visible=>true
,p_is_frozen=>false
);
wwv_flow_imp_page.create_ig_report_column(
 p_id=>wwv_flow_imp.id(3136260367377331725)
,p_view_id=>wwv_flow_imp.id(3136255341645331707)
,p_display_seq=>6
,p_column_id=>wwv_flow_imp.id(2544225698001299589)
,p_is_visible=>true
,p_is_frozen=>false
);
wwv_flow_imp_page.create_ig_report_column(
 p_id=>wwv_flow_imp.id(3136261218830331727)
,p_view_id=>wwv_flow_imp.id(3136255341645331707)
,p_display_seq=>7
,p_column_id=>wwv_flow_imp.id(2544225809928299590)
,p_is_visible=>true
,p_is_frozen=>false
);
wwv_flow_imp_page.create_ig_report_column(
 p_id=>wwv_flow_imp.id(3136262134000331730)
,p_view_id=>wwv_flow_imp.id(3136255341645331707)
,p_display_seq=>8
,p_column_id=>wwv_flow_imp.id(2544225968159299591)
,p_is_visible=>true
,p_is_frozen=>false
);
wwv_flow_imp_page.create_ig_report_column(
 p_id=>wwv_flow_imp.id(3136263064324331733)
,p_view_id=>wwv_flow_imp.id(3136255341645331707)
,p_display_seq=>9
,p_column_id=>wwv_flow_imp.id(2544226015731299592)
,p_is_visible=>true
,p_is_frozen=>false
);
wwv_flow_imp_page.create_ig_report_column(
 p_id=>wwv_flow_imp.id(3136267496639331748)
,p_view_id=>wwv_flow_imp.id(3136255341645331707)
,p_display_seq=>14
,p_column_id=>wwv_flow_imp.id(3136245880541328647)
,p_is_visible=>true
,p_is_frozen=>false
);
wwv_flow_imp_page.create_ig_report_column(
 p_id=>wwv_flow_imp.id(3150593123952904325)
,p_view_id=>wwv_flow_imp.id(3136255341645331707)
,p_display_seq=>0
,p_column_id=>wwv_flow_imp.id(3042467633054519863)
,p_is_visible=>true
,p_is_frozen=>false
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(3136246003783328648)
,p_plug_name=>'Enter Details'
,p_region_template_options=>'#DEFAULT#:t-Region--scrollBody'
,p_plug_template=>wwv_flow_imp.id(9836538334235038237)
,p_plug_display_sequence=>20
,p_query_type=>'TABLE'
,p_query_table=>'ER__SERVICE_INVOICE'
,p_include_rowid_column=>false
,p_is_editable=>false
,p_plug_source_type=>'NATIVE_FORM'
);
wwv_flow_imp_page.create_page_button(
 p_id=>wwv_flow_imp.id(3042467955842519866)
,p_button_sequence=>130
,p_button_plug_id=>wwv_flow_imp.id(3136246003783328648)
,p_button_name=>'GENERATE_INVOICE'
,p_button_action=>'SUBMIT'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>wwv_flow_imp.id(9836611983132038272)
,p_button_is_hot=>'Y'
,p_button_image_alt=>'Generate Invoice'
,p_button_position=>'CHANGE'
,p_button_condition=>'P28_SERVICE_INVOICE_ID'
,p_button_condition_type=>'ITEM_IS_NULL'
);
wwv_flow_imp_page.create_page_button(
 p_id=>wwv_flow_imp.id(3042468035320519867)
,p_button_sequence=>140
,p_button_plug_id=>wwv_flow_imp.id(3136246003783328648)
,p_button_name=>'UPDATE_INVOICE'
,p_button_action=>'SUBMIT'
,p_button_template_options=>'#DEFAULT#:t-Button--primary'
,p_button_template_id=>wwv_flow_imp.id(9836611983132038272)
,p_button_is_hot=>'Y'
,p_button_image_alt=>'Update Invoice'
,p_button_position=>'CHANGE'
,p_button_condition=>'P28_SERVICE_INVOICE_ID'
,p_button_condition_type=>'ITEM_IS_NOT_NULL'
);
wwv_flow_imp_page.create_page_button(
 p_id=>wwv_flow_imp.id(3042468145403519868)
,p_button_sequence=>150
,p_button_plug_id=>wwv_flow_imp.id(3136246003783328648)
,p_button_name=>'DELETE_INVOICE'
,p_button_action=>'SUBMIT'
,p_button_template_options=>'#DEFAULT#:t-Button--danger'
,p_button_template_id=>wwv_flow_imp.id(9836611983132038272)
,p_button_is_hot=>'Y'
,p_button_image_alt=>'Delete Invoice'
,p_button_position=>'CLOSE'
,p_button_condition_type=>'NEVER'
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(3136246227454328650)
,p_name=>'P28_SERVICE_INVOICE_ID'
,p_source_data_type=>'NUMBER'
,p_is_primary_key=>true
,p_is_query_only=>true
,p_item_sequence=>10
,p_item_plug_id=>wwv_flow_imp.id(3136246003783328648)
,p_item_source_plug_id=>wwv_flow_imp.id(3136246003783328648)
,p_source=>'SERVICE_INVOICE_ID'
,p_source_type=>'REGION_SOURCE_COLUMN'
,p_display_as=>'NATIVE_HIDDEN'
,p_is_persistent=>'N'
,p_protection_level=>'S'
,p_attribute_01=>'Y'
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(3136246324786328651)
,p_name=>'P28_SERVICE_INVOICE_REQUEST_ID'
,p_source_data_type=>'NUMBER'
,p_item_sequence=>20
,p_item_plug_id=>wwv_flow_imp.id(3136246003783328648)
,p_item_source_plug_id=>wwv_flow_imp.id(3136246003783328648)
,p_source=>'SERVICE_INVOICE_REQUEST_ID'
,p_source_type=>'REGION_SOURCE_COLUMN'
,p_display_as=>'NATIVE_HIDDEN'
,p_is_persistent=>'N'
,p_attribute_01=>'N'
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(3136246426161328652)
,p_name=>'P28_SERVICE_INVOICE_DATE'
,p_source_data_type=>'DATE'
,p_item_sequence=>60
,p_item_plug_id=>wwv_flow_imp.id(3136246003783328648)
,p_item_source_plug_id=>wwv_flow_imp.id(3136246003783328648)
,p_item_default=>'sysdate'
,p_item_default_type=>'EXPRESSION'
,p_item_default_language=>'PLSQL'
,p_prompt=>'Invoice Date'
,p_source=>'SERVICE_INVOICE_DATE'
,p_source_type=>'REGION_SOURCE_COLUMN'
,p_display_as=>'NATIVE_DISPLAY_ONLY'
,p_begin_on_new_line=>'N'
,p_field_template=>wwv_flow_imp.id(9836609223164038271)
,p_item_template_options=>'#DEFAULT#'
,p_is_persistent=>'N'
,p_attribute_01=>'Y'
,p_attribute_02=>'VALUE'
,p_attribute_04=>'Y'
,p_attribute_05=>'PLAIN'
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(3136246513899328653)
,p_name=>'P28_SERVICE_INVOICE_TOTAL_AMT'
,p_source_data_type=>'NUMBER'
,p_item_sequence=>90
,p_item_plug_id=>wwv_flow_imp.id(3136246003783328648)
,p_item_source_plug_id=>wwv_flow_imp.id(3136246003783328648)
,p_prompt=>'Total Amt'
,p_source=>'SERVICE_INVOICE_TOTAL_AMT'
,p_source_type=>'REGION_SOURCE_COLUMN'
,p_display_as=>'NATIVE_NUMBER_FIELD'
,p_cSize=>30
,p_begin_on_new_line=>'N'
,p_field_template=>wwv_flow_imp.id(9836609223164038271)
,p_item_template_options=>'#DEFAULT#'
,p_is_persistent=>'N'
,p_attribute_03=>'left'
,p_attribute_04=>'decimal'
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(3136246577922328654)
,p_name=>'P28_SERVICE_INVOICE_PAYMENT_DATE'
,p_source_data_type=>'DATE'
,p_is_required=>true
,p_item_sequence=>40
,p_item_plug_id=>wwv_flow_imp.id(3136246003783328648)
,p_item_source_plug_id=>wwv_flow_imp.id(3136246003783328648)
,p_item_default=>'sysdate'
,p_item_default_type=>'EXPRESSION'
,p_item_default_language=>'PLSQL'
,p_prompt=>'Invoice Payment Date'
,p_source=>'SERVICE_INVOICE_PAYMENT_DATE'
,p_source_type=>'REGION_SOURCE_COLUMN'
,p_display_as=>'NATIVE_DATE_PICKER_APEX'
,p_cSize=>30
,p_field_template=>wwv_flow_imp.id(9836609223164038271)
,p_item_template_options=>'#DEFAULT#'
,p_is_persistent=>'N'
,p_attribute_01=>'N'
,p_attribute_02=>'POPUP'
,p_attribute_03=>'NONE'
,p_attribute_06=>'NONE'
,p_attribute_09=>'N'
,p_attribute_11=>'Y'
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(3136246745690328655)
,p_name=>'P28_SERVICE_INVOICE_PAYMENT_METHOD'
,p_source_data_type=>'VARCHAR2'
,p_is_required=>true
,p_item_sequence=>70
,p_item_plug_id=>wwv_flow_imp.id(3136246003783328648)
,p_item_source_plug_id=>wwv_flow_imp.id(3136246003783328648)
,p_prompt=>'Payment Method'
,p_source=>'SERVICE_INVOICE_PAYMENT_METHOD'
,p_source_type=>'REGION_SOURCE_COLUMN'
,p_display_as=>'NATIVE_SELECT_LIST'
,p_lov=>'STATIC:Online;Online,Cash;Cash'
,p_lov_display_null=>'YES'
,p_cHeight=>1
,p_field_template=>wwv_flow_imp.id(9836609223164038271)
,p_item_template_options=>'#DEFAULT#'
,p_is_persistent=>'N'
,p_lov_display_extra=>'YES'
,p_attribute_01=>'NONE'
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(3136246829285328656)
,p_name=>'P28_CREATED_DATE'
,p_source_data_type=>'DATE'
,p_item_sequence=>100
,p_item_plug_id=>wwv_flow_imp.id(3136246003783328648)
,p_item_source_plug_id=>wwv_flow_imp.id(3136246003783328648)
,p_source=>'CREATED_DATE'
,p_source_type=>'REGION_SOURCE_COLUMN'
,p_display_as=>'NATIVE_HIDDEN'
,p_is_persistent=>'N'
,p_attribute_01=>'N'
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(3136246912874328657)
,p_name=>'P28_CREATED_BY'
,p_source_data_type=>'VARCHAR2'
,p_item_sequence=>110
,p_item_plug_id=>wwv_flow_imp.id(3136246003783328648)
,p_item_source_plug_id=>wwv_flow_imp.id(3136246003783328648)
,p_source=>'CREATED_BY'
,p_source_type=>'REGION_SOURCE_COLUMN'
,p_display_as=>'NATIVE_HIDDEN'
,p_is_persistent=>'N'
,p_attribute_01=>'N'
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(3136247048959328658)
,p_name=>'P28_UPDATED_DATE'
,p_source_data_type=>'DATE'
,p_item_sequence=>120
,p_item_plug_id=>wwv_flow_imp.id(3136246003783328648)
,p_item_source_plug_id=>wwv_flow_imp.id(3136246003783328648)
,p_source=>'UPDATED_DATE'
,p_source_type=>'REGION_SOURCE_COLUMN'
,p_display_as=>'NATIVE_HIDDEN'
,p_is_persistent=>'N'
,p_attribute_01=>'N'
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(3136247113650328659)
,p_name=>'P28_UPDATED_BY'
,p_source_data_type=>'VARCHAR2'
,p_item_sequence=>130
,p_item_plug_id=>wwv_flow_imp.id(3136246003783328648)
,p_item_source_plug_id=>wwv_flow_imp.id(3136246003783328648)
,p_source=>'UPDATED_BY'
,p_source_type=>'REGION_SOURCE_COLUMN'
,p_display_as=>'NATIVE_HIDDEN'
,p_is_persistent=>'N'
,p_attribute_01=>'N'
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(3136247222905328660)
,p_name=>'P28_STATUS'
,p_source_data_type=>'VARCHAR2'
,p_item_sequence=>80
,p_item_plug_id=>wwv_flow_imp.id(3136246003783328648)
,p_item_source_plug_id=>wwv_flow_imp.id(3136246003783328648)
,p_item_default=>'Y'
,p_source=>'STATUS'
,p_source_type=>'REGION_SOURCE_COLUMN'
,p_display_as=>'NATIVE_HIDDEN'
,p_is_persistent=>'N'
,p_attribute_01=>'N'
);
wwv_flow_imp_page.create_page_da_event(
 p_id=>wwv_flow_imp.id(3402767782580542245)
,p_name=>'calculate Total Price'
,p_event_sequence=>10
,p_triggering_element_type=>'COLUMN'
,p_triggering_region_id=>wwv_flow_imp.id(2544224980136299582)
,p_triggering_element=>'ER_SERVICE_INVOICE_DETAILS_SERVICE_QUANTITY,ER_SERVICE_INVOICE_DETAILS_ITEM_RATE'
,p_bind_type=>'bind'
,p_execution_type=>'IMMEDIATE'
,p_bind_event_type=>'change'
);
wwv_flow_imp_page.create_page_da_action(
 p_id=>wwv_flow_imp.id(3402767896301542246)
,p_event_id=>wwv_flow_imp.id(3402767782580542245)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_EXECUTE_PLSQL_CODE'
,p_attribute_01=>':ER__SERVICE_INVOICE_DETAILS_TOTAL_PRICE := :ER_SERVICE_INVOICE_DETAILS_SERVICE_QUANTITY * :ER_SERVICE_INVOICE_DETAILS_ITEM_RATE;'
,p_attribute_02=>'ER_SERVICE_INVOICE_DETAILS_SERVICE_QUANTITY,ER_SERVICE_INVOICE_DETAILS_ITEM_RATE,ER_SERVICE_INVOICE_DETAILS_SERVICE_QUANTITY'
,p_attribute_03=>'ER__SERVICE_INVOICE_DETAILS_TOTAL_PRICE'
,p_attribute_04=>'N'
,p_attribute_05=>'PLSQL'
,p_wait_for_result=>'Y'
);
wwv_flow_imp_page.create_page_da_event(
 p_id=>wwv_flow_imp.id(3402768056922542247)
,p_name=>'Calculate net total'
,p_event_sequence=>20
,p_triggering_element_type=>'COLUMN'
,p_triggering_region_id=>wwv_flow_imp.id(2544224980136299582)
,p_triggering_element=>'ER__SERVICE_INVOICE_DETAILS_TOTAL_PRICE,ER__SERVICE_INVOICE_DETAILS_TAX_AMT,ER__SERVICE_INVOICE_DETAILS_DISCOUNT_AMT'
,p_bind_type=>'bind'
,p_execution_type=>'IMMEDIATE'
,p_bind_event_type=>'change'
);
wwv_flow_imp_page.create_page_da_action(
 p_id=>wwv_flow_imp.id(3402768123919542248)
,p_event_id=>wwv_flow_imp.id(3402768056922542247)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_EXECUTE_PLSQL_CODE'
,p_attribute_01=>':ER__SERVICE_INVOICE_DETAILS_NET_TOTAL := :ER__SERVICE_INVOICE_DETAILS_TOTAL_PRICE + nvl(:ER__SERVICE_INVOICE_DETAILS_TAX_AMT,0) - nvl(:ER__SERVICE_INVOICE_DETAILS_DISCOUNT_AMT,0);'
,p_attribute_02=>'ER__SERVICE_INVOICE_DETAILS_TOTAL_PRICE,ER__SERVICE_INVOICE_DETAILS_TAX_AMT,ER__SERVICE_INVOICE_DETAILS_DISCOUNT_AMT'
,p_attribute_03=>'ER__SERVICE_INVOICE_DETAILS_NET_TOTAL'
,p_attribute_04=>'N'
,p_attribute_05=>'PLSQL'
,p_wait_for_result=>'Y'
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(3042468192348519869)
,p_process_sequence=>20
,p_process_point=>'AFTER_SUBMIT'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'INSERT/UPDATE DATA'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'begin',
'if :P28_SERVICE_INVOICE_ID is null then',
'Insert into ER__SERVICE_INVOICE (',
'    SERVICE_INVOICE_REQUEST_ID,',
'    SERVICE_INVOICE_DATE,',
'    SERVICE_INVOICE_TOTAL_AMT,',
'    SERVICE_INVOICE_PAYMENT_DATE,',
'    SERVICE_INVOICE_PAYMENT_METHOD,',
'    STATUS)',
'    values(',
'        :P28_SERVICE_INVOICE_REQUEST_ID,',
'        :P28_SERVICE_INVOICE_DATE,',
'        :P28_SERVICE_INVOICE_TOTAL_AMT,',
'        :P28_SERVICE_INVOICE_PAYMENT_DATE,',
'        :P28_SERVICE_INVOICE_PAYMENT_METHOD,',
'        :P28_STATUS',
'',
'    )',
'    RETURNING SERVICE_INVOICE_ID INTO :P28_SERVICE_INVOICE_ID;',
'',
'    Insert into ER_SERVICE_REQUEST_TRACKING(SERVICE_REQUEST_TRACKING_REQUEST_ID,',
'    SERVICE_REQUEST_TRACKING_ASSIGNED_EMPLOYEE_ID,',
'    SERVICE_REQUEST_TRACKING_STATUS,',
'    SERVICE_REQUEST_TRACKING_STATUS_UPDATE_DATE,',
'    STATUS)',
'    values',
'    (:P28_SERVICE_INVOICE_REQUEST_ID,',
'    :P0_USER_ID,',
'    ''Invoice Generated'',',
'    sysdate,',
'    ''Y'');',
'else',
'',
'update ER__SERVICE_INVOICE set',
'SERVICE_INVOICE_REQUEST_ID = :P28_SERVICE_INVOICE_REQUEST_ID,',
'    SERVICE_INVOICE_DATE = :P28_SERVICE_INVOICE_DATE,',
'    SERVICE_INVOICE_TOTAL_AMT = :P28_SERVICE_INVOICE_TOTAL_AMT,',
'    SERVICE_INVOICE_PAYMENT_DATE = :P28_SERVICE_INVOICE_PAYMENT_DATE,',
'    SERVICE_INVOICE_PAYMENT_METHOD = :P28_SERVICE_INVOICE_PAYMENT_METHOD,',
'    STATUS = :P28_STATUS',
'    where SERVICE_INVOICE_ID = :P28_SERVICE_INVOICE_ID;',
'    end if;',
'    end;'))
,p_process_clob_language=>'PLSQL'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_process_when=>'GENERATE_INVOICE,UPDATE_INVOICE'
,p_process_when_type=>'REQUEST_IN_CONDITION'
,p_internal_uid=>21197079019627357625
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(3042468289576519870)
,p_process_sequence=>30
,p_process_point=>'AFTER_SUBMIT'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'DELETE INVOICE'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'BEGIN',
'DELETE FROM ER__SERVICE_INVOICE WHERE SERVICE_INVOICE_ID = :P28_SERVICE_INVOICE_ID;',
'END;'))
,p_process_clob_language=>'PLSQL'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_process_when_button_id=>wwv_flow_imp.id(3042468145403519868)
,p_internal_uid=>21197079116855357626
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(3042467833569519865)
,p_process_sequence=>40
,p_process_point=>'AFTER_SUBMIT'
,p_region_id=>wwv_flow_imp.id(2544224980136299582)
,p_process_type=>'NATIVE_IG_DML'
,p_process_name=>'DETAILS - Save Interactive Grid Data'
,p_attribute_01=>'REGION_SOURCE'
,p_attribute_05=>'Y'
,p_attribute_06=>'Y'
,p_attribute_08=>'Y'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_process_when=>'GENERATE_INVOICE,UPDATE_INVOICE'
,p_process_when_type=>'REQUEST_IN_CONDITION'
,p_exec_cond_for_each_row=>'Y'
,p_internal_uid=>21197078660848357621
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(3136246140776328649)
,p_process_sequence=>10
,p_process_point=>'BEFORE_HEADER'
,p_region_id=>wwv_flow_imp.id(3136246003783328648)
,p_process_type=>'NATIVE_FORM_INIT'
,p_process_name=>'Initialize form MANAGE_INVOICE'
,p_internal_uid=>21290856968055166405
);
wwv_flow_imp.component_end;
end;
/
